# Generated by Django 5.2.5 on 2025-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foglalas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='time_interval',
            field=models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes')], default=60, help_text='Time slot interval in minutes'),
        ),
    ]
