# Generated by Django 5.2.5 on 2025-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foglalas', '0002_business_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('massage', 'Masszázs'), ('barber', 'Fodrász'), ('personal', 'Személyes konzultáció')], default='massage', max_length=20),
        ),
    ]
