# Generated by Django 5.2.5 on 2025-08-22 08:42

from django.db import migrations


def create_initial_businesses(apps, schema_editor):
    """Create initial business data with different time intervals"""
    Business = apps.get_model('foglalas', 'Business')
    
    businesses_data = [
        {
            'name': 'Stílus Fodrászat',
            'slug': 'stilus-fodraszat',
            'description': 'Professzionális fodrász szolgáltatások minden korosztály számára.',
            'address': '1052 Budapest, Váci utca 15.',
            'phone': '+36 1 234 5678',
            'email': 'info@stilusfodraszat.hu',
            'time_interval': 30,
        },
        {
            'name': 'Harmónia Masszázs Szalon',
            'slug': 'harmonia-masszazs',
            'description': 'Relaxáló masszázs és wellness szolgáltatások a belvárosban.',
            'address': '1051 Budapest, József Attila utca 12.',
            'phone': '+36 1 345 6789',
            'email': 'info@harmoniamasszazs.hu',
            'time_interval': 60,
        },
        {
            'name': 'Szakértői Tanácsadás',
            'slug': 'szakertoi-tanacsadas',
            'description': 'Személyre szabott konzultáció és szakértői tanácsadás.',
            'address': '1053 Budapest, Kossuth Lajos utca 8.',
            'phone': '+36 1 456 7890',
            'email': 'info@szakertoi-tanacsadas.hu',
            'time_interval': 60,
        }
    ]
    
    for business_data in businesses_data:
        # Only create if it doesn't exist (idempotent)
        if not Business.objects.filter(slug=business_data['slug']).exists():
            Business.objects.create(**business_data)


def reverse_create_initial_businesses(apps, schema_editor):
    """Remove the initial businesses if migration is reversed"""
    Business = apps.get_model('foglalas', 'Business')
    
    initial_slugs = [
        'stilus-fodraszat',
        'harmonia-masszazs',
        'szakertoi-tanacsadas'
    ]
    
    Business.objects.filter(slug__in=initial_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('foglalas', '0003_appointment_service_type'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_businesses,
            reverse_create_initial_businesses,
            elidable=True,  # This migration can be skipped if not needed
        ),
    ]
